package javaapplication1;


import Draw.DrawingArc;
import Draw.DrawingEllipse;
import Draw.DrawingFillRecatngle;
import Draw.DrawingLine;
import Draw.DrawingRectangle;
import Draw.DrawingShape;
import Draw.DrawingTriangle;
import Draw.IDrawShape;
import factory.ArcFactory;
import factory.EllipseFactory;
import factory.FillRecatangleFactory;
import factory.IFactory;
import factory.LineFactory;
import factory.RectangleFactory;
import factory.TrangleFactory;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import shape.drawing.Arc;
import shape.drawing.Ellipse;
import shape.drawing.FillRectangle;
import shape.drawing.Line;
import shape.drawing.Rectangle;
import shape.drawing.Shape;
import shape.drawing.Triangle;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Иван
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Map<String, IFactory> hm;
    Map<String, Integer> countDot;
    Map<String,Class> tableDrawing;
    Map<String, Shape> tableClass;
    List<Integer> ListDot;
    DrawingShape drawingShape = new DrawingShape (); 
    private int i = 1;

    public NewJFrame() {
        initComponents();
        
        
        
        
        tableClass = new HashMap<>();
        tableClass.put("линия", new Line());
        tableClass.put("элипс", new Ellipse());
        tableClass.put("прямоугольник",new Rectangle());
        tableClass.put("дуга",new Arc());
        tableClass.put("треугольник", new Triangle());
        tableClass.put("прямоугольник 2", new FillRectangle());
        
        
        
        
        hm = new HashMap<>();
        hm.put("линия", new LineFactory());
        hm.put("элипс", new EllipseFactory());
        hm.put("прямоугольник",  new RectangleFactory());
        hm.put("треугольник", new TrangleFactory());
        hm.put("дуга", new ArcFactory());
        hm.put("прямоугольник 2", new FillRecatangleFactory());

        countDot = new HashMap<>();
        countDot.put("линия", 2);
        countDot.put("элипс", 2);
        countDot.put("прямоугольник", 2);
        countDot.put("треугольник", 3);
        countDot.put("дуга", 2);
        countDot.put("прямоугольник 2", 2);

        ListDot = new ArrayList<>();

        choice1.add("прямоугольник");
        choice1.add("элипс");
        choice1.add("линия");
        choice1.add("дуга");
        choice1.add("прямоугольник 2");
        choice1.add("треугольник");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(702, 400));

        choice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choice1MouseClicked(evt);
            }
        });
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });

        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        canvas2.setBackground(new java.awt.Color(255, 255, 255));
        canvas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvas2MousePressed(evt);
            }
        });

        button1.setLabel("Очистка");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choice1MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        canvas2.update(canvas2.getGraphics());
        ListDot.clear();
        i = 1;
    }//GEN-LAST:event_button1ActionPerformed

    private void canvas2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas2MousePressed
        // TODO add your handling code here:
        if (i < countDot.get(choice1.getSelectedItem())) {
            ListDot.add(evt.getX());
            ListDot.add(evt.getY());
            i++;
        } else {
            ListDot.add(evt.getX());
            ListDot.add(evt.getY());
            IFactory s = hm.get(choice1.getSelectedItem());

            Shape shape = tableClass.get(choice1.getSelectedItem());
            shape.init(ListDot);
            IDrawShape drawShape = s.createShape();
            drawShape.paint(canvas2.getGraphics(), shape);
            ListDot.clear();
            i = 1;
        }
    }//GEN-LAST:event_canvas2MousePressed

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
        // TODO add your handling code here:
        ListDot.clear();
        i = 1;
    }//GEN-LAST:event_choice1ItemStateChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private java.awt.Choice choice1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
